version: "3.3"

services:

  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:4.4.4
    restart: always
    environment:
        - TZ=Etc/UTC
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ./docker/crafty/backups:/crafty/backups
        - ./docker/crafty/logs:/crafty/logs
        - ./docker/crafty/servers:/crafty/servers
        - ./docker/crafty/config:/crafty/app/config
        - ./docker/crafty/import:/crafty/import
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crafty.rule=Host(`nnci.fr`)"
      - "traefik.http.routers.crafty.entrypoints=web"
    depends_on:
      - "traefik"
